### ISSUE TITLE
`getComps()` uses `Final_Sample_Size_L` not `Final_Sample_Size`?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/PacFIN.Utilities#113]
The [documentation](https://github.com/pfmc-assessments/PacFIN.Utilities/blob/main/R/getComps.R#L12-L23) of `getComps()` says that it uses `Final_Sample_Size` but the code seems to only use `Final_Sample_Size_L`.

The `getComps()` function is providing good expansions because the value of `Final_Sample_Size_L` is set to the product of expansion factors 1 and 2 in `getExpansion_2()`: https://github.com/pfmc-assessments/PacFIN.Utilities/blob/497185807b910cbe6664d3171508e432fe473330/R/getExpansion_2.R#L195-L196 

**To Reproduce**
1. Run the attached script (relies on access to NWFSC server for data file): [test_pacfin_expansion.R.txt](https://github.com/pfmc-assessments/PacFIN.Utilities/files/11569914/test_pacfin_expansion.R.txt)
2. Note that changing `Final_Sample_Size` didn't impact the age or length comps, but changing `Final_Sample_Size_L` impacted both age and length comps. `Final_Sample_Size_A` doesn't seem to be used anywhere in the package.

**Expected behavior**
Either changing `Final_Sample_Size` should impact the comps or the documentation should be changed to clarify what sample size column to change. The only issue is if you want to provide a different calculation for `Final_Sample_Size` that the default, such as by changing the quantile passed to `capValues()` or using some other formula for the sample sizes.

**Comment by kellijohnson-NOAA** [comment]
Thank you @iantaylor-NOAA for reporting this lack of clarity. I think that there are multiple things going on here
- [ ] increase documentation for `get_comps()`
  - [ ] Create an example
  - [ ] Provide guidance on _L or _A
- [ ] ensure that arguments passed to `get_comps_long()` are actually being used and that things are not hard-coded
I will try to work this all out by Tuesday EOD.

**Comment by iantaylor-NOAA** [comment]
Thank you for taking this on @kellijohnson-NOAA. Looking around at the repositories for assessments being conducted now, I don't see folks changing the default Final_Sample_Size by very much so I think any changes will have only a minor impact. For petrale, I now understand how to create unexpanded comps for use in a sensitivity analysis using the status-quo package, but will happily revise the script as needed to work with any changes you make to this package to ensure things are reproducible in the future.

**Comment by kellijohnson-NOAA** [comment]
Thanks again @iantaylor-NOAA for reporting this. It appears to be strictly a documentation problem though I will admit I haven't worked all of the way through it yet. I hope to have a pull request to the package complete by tomorrow morning that updates the documentation. Users should be passing the column name that they want to use in `getComps_long(weightid = )` to `getComps(weightid = "")`. The default is `weightid = "Final_Sample_Size_L"`, which is why nothing changed for the age information. `Pdata` should have a column called `Final_Sample_Size_A` that should be used for age composition information.

**Comment by iantaylor-NOAA** [comment]
Good to hear that it won't be TOO much work to sort this out.
Thank you @kellijohnson-NOAA.

**Comment by brianlangseth-NOAA** [comment]
Im a little confused. Ian suggested that this is only an issue when doing something other than the defaults, but it also seems like it is an issue when doing age comps. Can you confirm whether age comps need to be recalculated after Kelli makes the fix (of course the effect is probably not an overly large one - so whether it "needs" to be done is relative).
