### ISSUE TITLE
Data request for species quillback rockfish 2025

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/PacFIN.Utilities#126]
### Identify the common name(s) or PacFIN species code(s)

quillback rockfish

Species code is nominally "QLBK" but the SPID field also has QLB1

### Type of data needed

catch, biological data

### Additional information

Want both catch and BDS information which are selected above

### Do you you have clearance to access these data?

- [X] I agree that I have clearance (as described above)

**Comment by chantelwetzel-noaa** [comment]
The data have been added to the network within a quillback rockfish folder in CurrentAssessments

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa.
