### ISSUE TITLE
Data request for species yellowtail rockfish

### ISSUE THREAD

**Issue by okenk** [pfmc-assessments/PacFIN.Utilities#130]
### Identify the common name(s) or PacFIN species code(s)

Yellowtail rockfish

### Type of data needed

catch, biological data

### Do you you have clearance to access these data?

- [X] I agree that I have clearance (as described above)

**Comment by kellijohnson-NOAA** [comment]
Thanks @okenk for submitting the data request through GitHub issues. If you navigate to the server at Assessments\CurrentAssessments\yellowtail_rockfish_south\data\pacfin you will find the requested data and a .qmd file that has been rendered into an html when I pulled the data. The html has the console output suggesting that there are some things you will want to discuss with the California rep regarding 2021 and 2022 biological data. Please let me know if you have any questions. I will leave it up to you to close the issue.

Please also feel free to provide feedback on the use of the .html file to convey/document information that I see when I pull the data. Or, would it be better to copy and paste it here as I did for Vlada 🤷? Thanks.

**Comment by okenk** [comment]
Thank you! Either method of sharing the .html file works for me!
