### ISSUE TITLE
Live vs. Dead Composition Data Expansion

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/PacFIN.Utilities#51]
Once live vs. dead is available in PacFIN bds data for all states we should think about how we would want to expand these data.  I think, generally, we would want to apply a stratification to keep them as a separate fleet (i.e., CA_Trawl_Live, CA_Trawl_Dead).  Some exploration should be done to understand if live and dead fish are combined on the same trip (maybe fish ticket is the right terminology) if there would be any issues attempting to expand these observations separately.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa are live fish always going to be their own fleet?

**Comment by aliwhitman** [comment]
got a notification here and wanted to chime in - I've had advice from folks at ODFW that live and dead fish are almost always captured on the same trip, so condition-delineated fleets may not be as appropriate as delineating by major gear type, for example. Is there a way to retain flexibility here? Happy to answer more questions...

**Comment by chantelwetzel-noaa** [comment]
Thank you @aliwhitman for chiming in. I agree with here we will need flexibility here, plus also some slightly sophisticated checks within the code to determine if expanding the live lengths is even possible. From my limited understanding I think in California there can be more specific targeting of smaller sized fish (plate size) in the live fishery, especially since live fish demand a much higher price per pound. In this case I could see the need for a live fish specific fleet but it would likely depend upon the proportion of the fish landed live versus dead.  Additionally, there is likely to be a lack of live fish lengths to inform selectivity which may be an issue for expansion (the code erroring out or expanded lengths that are non-sensical) potentially forcing assessors to hardwire a fixed selectivity pattern based on knowledge of the sizes targeted. I could see this assumption swaying some, depending upon the magnitude of live landings, from creating a separate fleet.

**Comment by iantaylor-NOAA** [comment]
There is a live-fish fishery for Shortspine Thornyhead in Southern California, but it was combined with the dead-fish fishery for purposes of the stock assessment. If there were enough data it might have been nice to treat them separately, however.

**Comment by kellijohnson-NOAA** [comment]
I emailed Brad about the status of this on 2023-05-08.

**Comment by chantelwetzel-noaa** [comment]
I had totally forgotten that we had an issue still on this topic. PacFIN has now resolved the issue of CA composition not having the disposition field populated. For the copper assessment this cycle, we used a life fish-only fleet and were able to expand the composition data based on the current expansion approach.

**Comment by kellijohnson-NOAA** [comment]
What is the column called in the composition data?

**Comment by chantelwetzel-noaa** [comment]
It is the "COND" column in the bds and the "DISPOSITION_CODE" in the catch data

**Comment by kellijohnson-NOAA** [comment]
Ahh, `PACFIN_CONDITION_CODE` where "A" is "alive". Thanks @chantelwetzel-noaa 😃.
