### ISSUE TITLE
Expand `doSexRatio()` to report what fraction of the samples were unsexed and modified

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/PacFIN.Utilities#73]
Expand `doSexRatio()` to report what fraction of the samples were unsexed and modified

_Originally posted by @iantaylor-NOAA in https://github.com/nwfsc-assess/PacFIN.Utilities/issues/19#issuecomment-486756450_

**Comment by iantaylor-NOAA** [comment]
`doSexRatio()` will be deprecated (see #50) so no need to expand it.
