### ISSUE TITLE
Is r cmd check needed?

### ISSUE THREAD

**Issue by k-doering-NOAA** [pfmc-assessments/PacFIN.Utilities#77]
**Is your feature request related to a problem? Please describe.**
I'm curious if it would be helpful to set up r cmd check on github actions for this or other pkgs in nwfsc-assess? I think it would be helpful if there are upstream dependencies that the pkg can easily become out of date with or if there are often install problems when people start trying to use pkgs again (e.g., at the start of a new assessment cycle)

**Describe the solution you'd like**
The easiest way to set it up would be either by using [`ghactions4r::use_r_cmd_check`](https://nmfs-fish-tools.github.io/ghactions4r/reference/use_r_cmd_check.html) or [`usethis::use_github_action_check_standard`](https://usethis.r-lib.org/reference/github_actions.html)

I would be happy to show the setup of either or both in one of the nwfsc office hrs, if it seems helpful!

**Describe alternatives you've considered**
It may be not necessary if the problems described are not of concern.

**Additional context**

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA for mentioning this. It is currently failing but I am going to set them up anyway 😉
