### ISSUE TITLE
Automation of recreational data

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/PacFIN.Utilities#78]
**Is your feature request related to a problem? Please describe.**
RecFIN data processing has been done with a combination of functions within PacFIN.Utilities and/or nwfscSurvey and is often done for each every dataset provided. Can we automate in some form like what is done within PacFIN or the data warehouse?

**Describe the solution you'd like**
Automate RecFIN data pulls and processing, especially for commonly used recreational data.

**Describe alternatives you've considered**
Alternatives to this include
1. continuing to use functions within PacFIN.Utilities and nwfscSurvey on a case by case basis for each recreational dataset we get, because the form of recreational data is not always the same depending on the person providing. 
2. generalizing PacFIN.Utilities and nwfscSurvey to apply generally for recreational data

**Comment by kellijohnson-NOAA** [comment]
Thanks @brianlangseth-NOAA for thinking about recreational data as well. I am going to attempt to work with @chantelwetzel-noaa to move all generalized composition functions to the survey package and make this package more about downloading and checking data from PacFIN. Then the recreational data package will be about downloading recreational data and getting data from @melissamonk-NOAA. I am going to close this issue b/c it is wrapped up into hundreds of other little issues but I wanted to let you know first that we are working on all that you outlined in hopes that it will be slightly better than it was for 2021 🥳
