### ISSUE TITLE
cleanPacFIN encountering error

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/PacFIN.Utilities#81]
**Describe the bug**
I cannot run cleanPacFIN. Gear groupings and state labels are fine. Error hits when trying to figure out SEX

Error in nwfscSurvey::codify_sex(data.vector = Pdata[, "SEX"]) : 
  unused argument (data.vector = Pdata[, "SEX"]) 

**To Reproduce**
1. load PacFIN bds file
2. run cleanPacFIN(loaded file....)
3. Error is as below

**Expected behavior**
I expect it to run and not get hung up

**Screenshots**
![image](https://user-images.githubusercontent.com/27824606/213297425-e6ea252d-b4b8-489e-91b8-0dd747c5135f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - R version 4.2.2
 - Installed PacFIN.Utilities from github just today

**Comment by brianlangseth-NOAA** [comment]
My version of the nwfscSurvey package had the same SHA1 code as the current one so that did not appear to be the issue. 

I reinstalled PacFIN.Utilities incorporating a new change (commit a30e33d) and the script runs and works as expected. Thank you @chantelwetzel-noaa and @kellijohnson-NOAA.

**Comment by kellijohnson-NOAA** [comment]
Thanks for checking @brianlangseth-NOAA and sorry for the :bug: in the first place.
