### ISSUE TITLE
Washington State Black rockfish (Sebastes melanops)

### ISSUE THREAD

**Issue by shcaba** [pfmc-assessments/PacFIN.Utilities#85]
### Identify the common name(s) or PacFIN species code(s)

I don't know the species code, but this is a request for catches and bio data for **black rockfish** in **Washington State** only.

### Type of data needed

catch, biological data

### Do you you have clearance to access these data?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA I am happy to do this for @shcaba.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa!

**Comment by chantelwetzel-noaa** [comment]
Completed
