### ISSUE TITLE
Data request for Rex Sole

### ISSUE THREAD

**Issue by emilysellinger** [pfmc-assessments/PacFIN.Utilities#86]
### Identify the common name(s) or PacFIN species code(s)

Rex sole (Glyptocephalus zachirus)
PacFIN species codes:
REX
REX1

### Type of data needed

catch, biological data

### Additional information

@chantelwetzel-noaa has volunteered to pull this data (UW stock assessment class)

### Do you you have clearance to access these data?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
Completed and sent to @okenk, Owen, and Vlada.

**Comment by kellijohnson-NOAA** [comment]
Linking #98 to this data request.
