### ISSUE TITLE
Data request for shortspine thornyhead

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [pfmc-assessments/PacFIN.Utilities#88]
### Identify the common name(s) or PacFIN species code(s)

**For sure we want shortspine thornyhead catch**
GRND ROCK TRNY SSP1            NOM. SHORTSPINE THORNYHEA SEBASTOLOBUS SPP.                
GRND ROCK TRNY SSPN            SHORTSPINE THORNYHEAD     SEBASTOLOBUS ALASCANUS   

**We may also want the rare species or grouped thornyhead catch**
GRND ROCK TRNY                 __THORNYHEADS COMPLEX     SEBASTOLOBUS SPP.                
GRND ROCK TRNY LSP1            NOM. LONGSPINE THORNYHEAD SEBASTOLOBUS SPP.                
GRND ROCK TRNY LSPN            LONGSPINE THORNYHEAD      SEBASTOLOBUS ALTIVELIS               
GRND ROCK TRNY THD1            NOM. THORNYHEADS          SEBASTOLOBUS SPP.                
GRND ROCK TRNY THDS            THORNYHEADS (MIXED)       SEBASTOLOBUS SPP.

### Type of data needed

catch, biological data

### Additional information

Landings
Biological data (landings length compositions)

@chantelwetzel-noaa / @kellijohnson-NOAA this is for the assessment class. May want to route through @okenk, Owen, or Vlada. Thank you for your help!

### Do you you have clearance to access these data?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
I have pulled the species specific data from pacfin for SSPN. I have not had an opportunity to look into these other various species categories. I have posted these data in the shortspine thornyhead folder in the "2023 Assessment Cycle" folder on the network.

**Comment by okenk** [comment]
Thanks Chantel. I found them on the network and shared them with all students who have signed PacFIN relases via kiteworks.

**Comment by JaneSullivan-NOAA** [comment]
Thank you both!

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA  FYI: I also checked for the "THDS" and "THD1". Only catch data was returned for the "THDS".  This file was also posted to the network yesterday.

**Comment by kellijohnson-NOAA** [comment]
I did a quick search in the bds data for "thorny" in PACFIN_SPECIES_COMMON_NAME and the only PACFIN_SPECIES_CODEs that come up with records are LSP1, LSPN, THDS, SSPN. With respect to the catch data, there were also records for SSP1. I think @chantelwetzel-noaa has provided all of these.

@JaneSullivan-NOAA, if you could either close this issue or comment with respect to what we still haven't provided that would be super helpful.

**Comment by JaneSullivan-NOAA** [comment]
@kellijohnson-NOAA I think we are all set. Thanks for all your help!
