### ISSUE TITLE
Data request for longspine thornyhead

### ISSUE THREAD

**Issue by haleyoleynik** [pfmc-assessments/PacFIN.Utilities#92]
### Identify the common name(s) or PacFIN species code(s)

LSP1 NOM., LONGSPINE THORNYHEAD, SEBASTOLOBUS SPP.      
LSPN, LONGSPINE THORNYHEAD, SEBASTOLOBUS ALTIVELIS           

### Type of data needed

catch

### Additional information

Hi @chantelwetzel-noaa / @kellijohnson-NOAA! We're looking for **landings data only for longspine thornyheads** so that we can calc the coastwise proportion of shortspines to apply to the unidentified thornyhead catches (which we already have!).

This is for the UW assessment class. @okenk shared the data with the class via kite works last time, so you can put it in the shortspine thornyhead folder in the "2023 Assessment Cycle" like you did last time - if that was easy and it works for you, @okenk. Let me know if you have questions! 

Thank you!!!! 

### Do you you have clearance to access these data?

- [X] I agree that I have clearance

**Comment by kellijohnson-NOAA** [comment]
@haleyoleynik I will get you the data some time today :)

**Comment by kellijohnson-NOAA** [comment]
The data which I pulled using
```
PullCatch.PacFIN("LSPN",addnominal = TRUE, verbose = TRUE)
```
are on the drive for @okenk to distribute.
